### ISSUE TITLE
Ceiling bug 

### ISSUE THREAD

**Issue by imbackgaming** [FlodGamedev/OceanCraftBugtracker#17] opened 2021-02-20 09:59 UTC
1) play as normal
2) build a ceiling above you 
3) die when you die your stuff will be teleported above you 

https://youtu.be/6Z2IXxrt9FY

**Comment by FlodGamedev** [comment] 2021-02-20 16:11
duplicate of #12

**Closed as completed by FlodGamedev** 2021-02-20 16:11 UTC
